=== Reyzirk/integrativeProgramming/XML/courses.xsd
<?xml version="1.0"?>
<!--
============================================
Copyright 2022 Omega International Junior School. All Right Reserved.
Web Application is under GNU General Public License v3.0
============================================
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="courses">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="course" type="courseDetail" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="courseDetail">
        <xs:sequence>
            <xs:element name="name" type="xs:string" />
            <xs:element name="desc" type="xs:string"/>
            <xs:element name="CourseMaterials" type="courseMaterials" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="code" type="xs:string" use="required"></xs:attribute>
    </xs:complexType>
    <xs:complexType name="courseMaterials">
        <xs:sequence>
            <xs:element name="CourseMaterial" type="courseMaterial" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="courseMaterial">
        <xs:sequence>
            <xs:element name="name" type="xs:string" />
            <xs:element name="link" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required"></xs:attribute>
    </xs:complexType>
</xs:schema>

=== Reyzirk/integrativeProgramming/XML/courses.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
============================================
Copyright 2022 Omega International Junior School. All Right Reserved.
Web Application is under GNU General Public License v3.0
============================================
//Author: Poh Choo Meng
-->
<?xml-stylesheet type="text/xsl" href="courselist.xsl"?>
<courses xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="courses.xsd">

<course code="BAIT2073"><name>MOBILE APPLICATION DEVELOPMENT</name><desc>&lt;p&gt;Learning the mobile apps &lt;strong&gt;(Kotlin)&lt;/strong&gt;&lt;/p&gt;</desc><CourseMaterials><CourseMaterial id="CM6260259630e997.56338391"><name>BAIT2073 Practical List 202109 </name><link>6260256e25e390.66939264.pdf</link></CourseMaterial></CourseMaterials></course><course code="BAIT2123"><name>Internet of Things</name><desc>&lt;p&gt;Learn the fundamentals knowledge of IoT&lt;/p&gt;</desc><CourseMaterials><CourseMaterial id="CM6260271f74dae4.54707747"><name>LED Fritzing</name><link>6260271f738171.79318369.fzz</link></CourseMaterial></CourseMaterials></course><course code="MPU2030"><name>English</name><desc>&lt;p&gt;Basic english learning&lt;/p&gt;</desc></course><course code="CHI1021"><name>Fundamentals of Chinese</name><desc>&lt;p&gt;Learning the basic knowledge of Chinese language&lt;/p&gt;</desc></course></courses>
