=== Reyzirk/integrativeProgramming/XML/grades.xsd
<?xml version="1.0"?>
<!--
============================================
Copyright 2022 Omega International Junior School. All Right Reserved.
Web Application is under GNU General Public License v3.0
============================================
//Author: Poh Choo Meng
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="grades">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="grade" type="gradeDetail" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="gradeDetail">
        <xs:sequence>
            <xs:element name="grade" type="xs:string" />
            <xs:element name="minMark" type="xs:decimal"/>
            <xs:element name="maxMark" type="xs:decimal"/>
        </xs:sequence>
        <xs:attribute name="gradeID" type="xs:string" use="required"></xs:attribute>
    </xs:complexType>
</xs:schema>

=== Reyzirk/integrativeProgramming/XML/grades.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
============================================
Copyright 2022 Omega International Junior School. All Right Reserved.
Web Application is under GNU General Public License v3.0
============================================
-->
<grades xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="grades.xsd">
<grade gradeID="90"><grade>Z</grade><minMark>90</minMark><maxMark>95</maxMark></grade><grade gradeID="G622e32f8a84fc0.36559885"><grade>AAA</grade><minMark>6</minMark><maxMark>9</maxMark></grade><grade gradeID="0"><grade>uy</grade><minMark>0</minMark><maxMark>5</maxMark></grade><grade gradeID="G6235eed6287ea0.69086431"><grade>Z</grade><minMark>51</minMark><maxMark>55</maxMark></grade><grade gradeID="G6235eee8509c34.07492026"><grade>E</grade><minMark>48</minMark><maxMark>48</maxMark></grade><grade gradeID="G6235f059756cf6.42414381"><grade>ZA</grade><minMark>41</minMark><maxMark>45</maxMark></grade><grade gradeID="G62387ec26a6559.87113674"><grade>AAB</grade><minMark>10</minMark><maxMark>13</maxMark></grade></grades>
